Ext auth service : remove `split_words` to honor `KOURIER_EXTAUTHZ*` env vars
knative-sandbox/net-kourier pull request #785
Opened 2022-03-06 14:37 UTC by norbjd

# Changes

:bug: Ext auth service : remove `split_words` to honor `KOURIER_EXTAUTHZ*` env vars

/kind bug

With this fix, `KOURIER_EXTAUTHZ_FAILUREMODEALLOW` and `KOURIER_EXTAUTHZ_MAXREQUESTBYTES` env vars are honored as the docs states. Before that, users should set `KOURIER_EXTAUTHZ_FAILURE_MODE_ALLOW` and `KOURIER_EXTAUTHZ_MAX_REQUEST_BYTES` (notice the separating `_`) to change those parameters (see [envconfig `split_words` documentation](https://github.com/kelseyhightower/envconfig/blob/v1.4.0/README.md#struct-tag-support)).

**Release Note**

No impacts on clients if they were following the [`README.md`](./README.md).

**Docs**

No docs.

2022-03-07 01:40 UTC, nak3 requested changes
I think this is a docs bug and we should fix README rather than code.

> No impacts on clients if they were following the [config of ext auth in the README.md](https://github.com/knative-sandbox/net-kourier/blob/a95fd30/README.md#external-authorization-configuration).

If they were following the README.md, the configuration does not work, does it?

2022-03-07 11:53 UTC, norbjd commented
Hello @nak3 !

As of now, if users are following this part in the README.md:

> KOURIER_EXTAUTHZ_FAILUREMODEALLOW*: Allow traffic to go through if the ext auth service is down. Accepts true/false
> KOURIER_EXTAUTHZ_MAXREQUESTBYTES: Max request bytes, if not set, defaults to 8192 Bytes. More info [Envoy Docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=max_request_bytes#extensions-filters-http-ext-authz-v3-buffersettings)

Then their parameters are not used in Kourier. But there is no error, so users could think that they have correctly change the parameters.

To be taken into account by Kourier, they have to set instead:

- `KOURIER_EXTAUTHZ_FAILURE_MODE_ALLOW`
- `KOURIER_EXTAUTHZ_MAX_REQUEST_BYTES`

which is not documented anywhere. They have to dig into the code to find those values.

I have changed the actual behavior instead of the docs, because I don't want this to be a breaking change for former users of `KOURIER_EXTAUTHZ_FAILUREMODEALLOW` and `KOURIER_EXTAUTHZ_MAXREQUESTBYTES`. To my opinion (but I might be wrong), people tend to follow the docs instead of diving into the source code.

Anyway, both approaches are ok, so tell me the approach you prefer! Note that if we change the docs, we have to inform users using these env vars to change them (add underscores).

2022-03-07 12:31 UTC, nak3 commented
/ok-to-test

Thank you for your explanation. 
In addition to your comment, as per this commit history https://github.com/knative-sandbox/net-kourier/commit/2926c6a4461c3cf087face6c8b31c4cf3e5e1eec, `KOURIER_EXTAUTHZ_FAILUREMODEALLOW` and `KOURIER_EXTAUTHZ_MAXREQUESTBYTES` were originally expected (you might already know :sweat_smile: ), so let's use your change.

2022-03-08 12:27 UTC, nak3 commented
@norbjd Just in case, is it alright to merge this after v1.3 release? Today is the [v1.3 release day](https://github.com/knative/release#schedule) (I think it will start when US folks are on-line) so I am hesitate to merge this just before the release.

2022-03-08 17:12 UTC, norbjd commented
That's ok for me @nak3 ! Let's merge this after the v1.3.0 release :wink:

2022-03-09 06:00 UTC, nak3 commented
/lgtm
/approve

2022-03-09 06:18 UTC, merged